import {
    Shapes,
    IdCard,
    FileText,
    RectangleHorizontal,
    LayoutGrid,
    Type,
    BookOpen,
    Palette,
    Puzzle,
    Presentation,
    LayoutTemplate,
    Mails,
    PenTool,
    Projector,
    Video,
    FileCode,
    ShoppingCart,
    Settings,
    Handshake,
    UserCheck,
    MonitorCog,
    TabletSmartphone,
    Laptop,
    Smartphone,
    TrendingUp,
    Rocket,
    SquareMousePointer,
    Megaphone,
    SquarePlay,
    BookCheck,
    SearchCode,
    Webhook,
    Ratio,
    Slack,
    BadgePercent,
} from "lucide-react";

export const ICONS = {
    Shapes,
    IdCard,
    FileText,
    RectangleHorizontal,
    LayoutGrid,
    Type,
    BookOpen,
    Palette,
    Puzzle,
    Presentation,
    LayoutTemplate,
    Mails,
    PenTool,
    Projector,
    Video,
    FileCode,
    ShoppingCart,
    Settings,
    Handshake,
    UserCheck,
    MonitorCog,
    TabletSmartphone,
    Laptop,
    Smartphone,
    TrendingUp,
    Rocket,
    SquareMousePointer,
    Megaphone,
    SquarePlay,
    BookCheck,
    SearchCode,
    Webhook,
    Ratio,
    Slack,
    BadgePercent,
} as const;

export type IconName = keyof typeof ICONS;